const projects=[
['RAG / AVIATION','AI NOTAM Assistant','Making aviation notices searchable in plain English.',['FastAPI','Pinecone','Next.js','FAA API'],'Built during my internship at the Airports Authority of India, this RAG assistant enables conversational queries over live Notice to Air Missions data from the FAA API. I also prepared a mentor-approved six-week delivery roadmap.',['FAA notices','Vector retrieval','Plain-English answers']],
['LOCAL AI / PRIVACY','AI Resume Chatbot','A conversation with your resume, powered by local AI.',['Ollama','LangChain','ChromaDB','Flask'],'A privacy-focused RAG system that processes PDF and DOCX resumes into semantic embeddings using nomic-embed-text. Locally hosted Llama 3.1 and Qwen 2.5 models serve answers through Flask REST APIs, with multi-turn conversation history.',['PDF / DOCX','Local embeddings','Contextual answers']],
['AGENTIC AI / KNOWLEDGE','Agentic Note-Taking Assistant','Connecting notes, reasoning, and autonomous tool use.',['RAG','FAISS','ChromaDB','AI agents'],'An agent-based assistant with a retrieval-augmented generation pipeline, supporting multi-step reasoning and autonomous tool use. FAISS and ChromaDB support retrieval from stored knowledge.',['Knowledge base','Retrieval & reasoning','Tool-assisted response']],
['AIoT / SUSTAINABILITY','Intelligent Soilless Farming','Connecting plant health, environmental data, and automation.',['IoT sensors','Computer vision','ML','Automation'],'An AIoT architecture for hydroponics and aeroponics, combining multi-sensor environmental monitoring with automation. Computer vision supports plant-health monitoring and machine learning supports crop optimization. The framework was formalized in a published research paper.',['Sensor readings','Plant-health analysis','Growing decisions']]
];
document.querySelector('#content').innerHTML=`
<section class="section wrap" id="work"><div class="section-heading reveal"><div><p class="eyebrow">01 / SELECTED WORK</p><h2>Built to solve.<br><span>Designed to matter.</span></h2></div><p>Exploring the space between intelligent software and the physical world.</p></div><div class="projects">${projects.map((p,i)=>`<article class="project reveal"><div class="project-art art-${i}"><span class="project-number">0${i+1}</span><div class="pipeline">${p[5].map((v,k)=>`<div><span class="step-index">0${k+1}</span>${v}</div>`).join('<i></i>')}</div><span class="art-caption">SYSTEM ARCHITECTURE / ${p[0]}</span></div><div class="project-info"><p class="eyebrow">${p[0]}</p><h3>${p[1]}</h3><p>${p[2]}</p><div class="tags">${p[3].map(x=>`<span>${x}</span>`).join('')}</div><button class="detail-button" data-project="${i}" aria-haspopup="dialog">Explore project <span>+</span></button></div></article>`).join('')}</div><a class="text-link" href="https://github.com/Dhruvhash" target="_blank" rel="noopener noreferrer">Explore my GitHub profile</a></section>
<section class="research section" id="research"><div class="wrap"><div class="section-heading reveal"><div><p class="eyebrow">02 / RESEARCH</p><h2>Curiosity,<br><span>put to the test.</span></h2></div><p>Four published papers across connected agriculture, privacy-preserving learning, and image forensics.</p></div><div class="papers">${[
['AIoT & AGRICULTURE','Optimizing Hydroponics and Aeroponics through AIoT','Multi-sensor arrays, automation, computer vision, solar backup, and data encryption.','Connected farming'],
['PRIVACY & CLIMATE','Differentially Private Blockchain-Based Climate Forecasting','DP-SGD-trained LSTM with attention and SHA-256 hashing for tamper-proof storage.','0.0774 RMSE'],
['FEDERATED LEARNING','Blockchain-Enabled Federated Learning for Digital Metrology','BFL-Metrology combines federated learning with blockchain-based data integrity.','99.6% integrity verification'],
['VISION TRANSFORMERS','Detecting AI-Generated and Altered Images','Vision-transformer forensic learning with FFT and DCT frequency-domain analysis.','0.98 AUC']
].map((p,i)=>`<article class="paper reveal"><span class="paper-num">0${i+1}</span><div><p class="eyebrow">${p[0]}</p><h3>${p[1]}</h3><p>${p[2]}</p></div><span class="paper-stat">${p[3]}</span></article>`).join('')}</div><p class="research-note">Research summaries and reported results from my resume.</p></div></section>
<section class="section wrap" id="about"><div class="section-heading reveal"><div><p class="eyebrow">03 / ABOUT ME</p><h2>A builder’s mindset.<br><span>A researcher’s curiosity.</span></h2></div></div><div class="about-grid"><div class="reveal"><p class="about-intro">I’m Dhruv, a Computer Science undergraduate at Maharaja Surajmal Institute of Technology, Delhi.</p><p class="muted">My work connects ML engineering, embedded systems, and applied research. I enjoy taking a problem from literature review through implementation and evaluation—then finding out how it behaves in the real world.</p><div class="education"><span>B.TECH / COMPUTER SCIENCE</span><strong>MSIT, Delhi</strong><span>2024–2028</span></div><h3 class="toolkit-heading">My toolkit</h3><div class="skills">${['Python','C / C++','Java','RAG & LangChain','Ollama','PyTorch','Computer vision','Federated learning','ESP32','Raspberry Pi','FreeRTOS','MQTT'].map(x=>`<span>${x}</span>`).join('')}</div></div><div class="timeline reveal"><article><p class="eyebrow">JUN–JUL 2026</p><h3>Airports Authority of India</h3><span>IT / Software Department Intern</span><p>Built the AI NOTAM Assistant at the Northern Regional HQ, combining live aviation data with retrieval-augmented generation.</p></article><article><p class="eyebrow">MAY–JUN 2026</p><h3>ElevanceSkills</h3><span>IoT Intern · Remote</span><p>Built and simulated an ESP32 patient-monitoring system with FreeRTOS, MQTT telemetry, medication alerts, and offline buffering.</p></article><article><p class="eyebrow">LEADERSHIP & COMMUNITY</p><h3>Building together</h3><p>Hardware / Robotics Lead at Melerigamy Teach Group, Hardware Project Committee at IEEE MSIT, and former hardware member of Eyantra MSIT.</p></article></div></div></section>
<section class="contact wrap reveal" id="contact"><p class="eyebrow">04 / WHAT’S NEXT?</p><h2>Let’s build something<br><span>worth exploring.</span></h2><p>Interested in AI, research, or connected systems?<br>I’m available for part-time remote work, including evenings and nights.</p><a class="email" href="mailto:dhruv_cse_28@msit.in">dhruv_cse_28@msit.in</a><div class="actions"><a class="button primary" href="https://www.linkedin.com/in/dhruv-ghosal-841353247/" target="_blank" rel="noopener noreferrer">Connect on LinkedIn</a><a class="button" href="https://github.com/Dhruvhash" target="_blank" rel="noopener noreferrer">Find me on GitHub</a></div></section><footer class="wrap"><a class="logo" href="#home">dg<span>.</span></a><span>© ${new Date().getFullYear()} Dhruv Ghosal</span><a href="#home">Back to top</a></footer>
<dialog id="project-dialog" aria-labelledby="dialog-title"><button class="close-dialog" aria-label="Close project details">×</button><p class="eyebrow" id="dialog-type"></p><h2 id="dialog-title"></h2><p id="dialog-body"></p><div class="tags" id="dialog-tags"></div><a class="button primary" href="https://github.com/Dhruvhash" target="_blank" rel="noopener noreferrer">Visit my GitHub profile</a></dialog>`;
const dialog=document.querySelector('dialog');document.querySelectorAll('[data-project]').forEach(b=>b.addEventListener('click',()=>{const p=projects[Number(b.dataset.project)];document.querySelector('#dialog-title').textContent=p[1];document.querySelector('#dialog-type').textContent=p[0];document.querySelector('#dialog-body').textContent=p[4];document.querySelector('#dialog-tags').innerHTML=p[3].map(s=>`<span>${s}</span>`).join('');dialog.showModal()}));document.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>{e.classList.add('animate');observer.observe(e)})}

